# This is a workflow which sends a post request to the server containing the student's grade upon closing of the homework issue 
name: Post HW Grade

on:
  issues:
    types: [closed]

jobs:
  send-post:
    if: github.event.issue.user.login != github.event.sender.login
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Web Request Action
        uses: satak/webrequest-action@master
        with:
          url: https://cpu-processor-dev.azurewebsites.net/api/Api/GitHubData
          method: POST
          payload: '{"githubkey": "${{ github.event.repository.name }}", "mark": "${{ github.event.issue.title }}", "extracredit": "${{ github.event.issue.labels[0].name }}"}'
      - name: Web Request Action
        uses: satak/webrequest-action@master
        with:
          url: https://cpu-processor.azurewebsites.net/api/Api/GitHubData
          method: POST
          payload: '{"githubkey": "${{ github.event.repository.name }}", "mark": "${{ github.event.issue.title }}", "extracredit": "${{ github.event.issue.labels[0].name }}"}'
